[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
elara = "4LhEEtzAhM6wEXJR2YQHPEs79UEx8e6HncmeHbqbW1w1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test-cancel = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/elara/cancel.test.ts"
test-ata = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/elara/ata.test.ts"
test-init = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/elara/init.test.ts"
test-fill = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/elara/fill.test.ts"
test-partial = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/elara/partial-fill.test.ts"
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
