[package]
name = "lumenn"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "lumenn"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
anchor-spl = { version = "0.31.1", features = ["idl-build"] }
light-sdk = { version = "0.13.0", features = ["anchor"] }
light-hasher = { version = "3.0.0", features = ["solana"] }
light-sdk-types = "0.13.0"
solana-security-txt = "1.1.1"
